apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: '2020-10-10T19:57:46Z'
  name: jmeter-test-suite
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jmeter-test-suite:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/mohhef/jmeter-test'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'openjdk:8-jre-slim'
    type: Docker
  triggers:
    - github:
        secret: 1802aa5420b11b2c
      type: GitHub
status:
  lastVersion: 4
