apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: '2020-10-10T19:57:46Z'
  name: jmeter-test-suite
  namespace: jmeter-test
  resourceVersion: '75196'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/jmeter-test/buildconfigs/jmeter-test-suite
  uid: ddcb76f9-0b32-11eb-b601-00155d380100
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jmeter-test-suite:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/mohhef/jmeter-test'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'ubuntu:16.04'
    type: Docker
  triggers:
    - github:
        secret: 1802aa5420b11b2c
      type: GitHub
status:
  lastVersion: 4
