apiVersion: v1
kind: Template
metadata:
  name: jmeter-test-suite
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: jmeter-test-suite
    labels:
      jobName: jmeter-test-suite
  spec:
    completions: 1
    parallelism: 1
    template:
      metadata:
        name: jmeter-test-suite
        labels:
          jobName: jmeter-test-suite
      spec:
        containers:
        - name: jmeter-test-suite
          image: "192.168.2.37:8443/jj-jenkins/jmeter-test-suite"
          command:
          - /jmeter/runjob.sh
          args:
          - HttpRequest
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        securityContext: {}
        terminationGracePeriodSeconds: 30
# parameters:
# - description: Test file name
#   name: FILE_NAME
#   required: true
# - description: JMeter image from specific cluster/project
#   name: IMAGE
#   required: true
#   value: jmeter-test-suite